### ISSUE TITLE
List dependencies in the README

### ISSUE THREAD

**Issue by Spaghetti-Cat** [blueyed/awesome-cyclefocus#8]
Hello,

I couldn't get this working because I was still running v3.4.X which doesn't have the `gears` module introduced in v3.5. For me not updating was voluntary but I see that even Ubuntu repos are still at v3.4.X.

So it would be good to list the dependencies in the "Installation" section of the README:

awesomewm 3.5 and upwards

**Comment by blueyed** [comment]
Makes sense, although gears is not really required IIRC.

**Comment by Spaghetti-Cat** [comment]
I had this error on the line where `local cyclefocus = require('cyclefocus')` was put so I assumed `gears` was a dep:

/home/danb/.config/awesome/cyclefocus/init.lua:11: module 'gears' not found:
        no field package.preload['gears']
        no file './gears.lua'
        no file '/usr/share/lua/5.1/gears.lua'
        no file '/usr/share/lua/5.1/gears/init.lua'
        no file '/usr/lib/lua/5.1/gears.lua'
        no file '/usr/lib/lua/5.1/gears/init.lua'
        no file '/home/danb/.config/awesome/gears.lua'
        no file '/home/danb/.config/awesome/gears/init.lua'
        no file '/etc/xdg/awesome/gears.lua'
        no file '/etc/xdg/awesome/gears/init.lua'
        no file '/usr/share/awesome/lib/gears.lua'
        no file '/usr/share/awesome/lib/gears/init.lua'
        no file './gears.so'
        no file '/usr/lib/lua/5.1/gears.so'
        no file '/usr/lib/lua/5.1/loadall.so'

**Comment by blueyed** [comment]
I've thought it might have been used for debugging only, but it's used for the icon:

            preset.icon = gears.surface.load(args.client.icon) -- using gears prevents memory leaking

It was added in f3720b5, and is "only" meant to prevent memory leaks.

So that might be something that could fall back to not using gears.

Do you want to give this a try?
Comment the `require("gears")` line, and just use:

    preset.icon = args.client.icon

**Comment by blueyed** [comment]
@Spaghetti-Cat 
Can you test current master (https://github.com/blueyed/awesome-cyclefocus/commit/b69505cea7f8426ee519a7801cce34d95774a708)?

**Comment by Spaghetti-Cat** [comment]
I tried the workaround you posted about commenting the `gears` dependency etc. with commit `9a6931` but got the following error when awesomewm executes `rc.lua` on the `require('cyclefocus')` line:
    /home/danb/.config/awesome/cyclefocus/init.lua:224: attempt to call field 'connect_signal' (a nil value)

I get this exact same error when I tried the latest master `b69505c`.

**Comment by blueyed** [comment]
@Spaghetti-Cat 
Sorry for not responding earlier: is this still an issue for you?

**Comment by Spaghetti-Cat** [comment]
@blueyed No problem, unfortunately I still get the error with latest master:

/home/danb/.config/awesome/cyclefocus/init.lua:224: attempt to call field 'connect_signal' (a nil value)

**Comment by blueyed** [comment]
@Spaghetti-Cat 
Should be fixed in https://github.com/blueyed/awesome-cyclefocus/commit/c4e898b36843071e7da5bf0923c58094aedbf3ba.

btw: I have a lot of local changes, where I've moved over to using wiboxes instead of naughty for the display.  I hope to get this ready in the next weeks.

**Comment by Spaghetti-Cat** [comment]
Sadly, the error persists. I double-checked the installation instructions, deleted cyclefocus, re-cloned it, made sure that HEAD of master was `c4e89`.

  /home/danb/.config/awesome/cyclefocus/init.lua:224: attempt to call field 'connect_signal' (a nil value)

**Comment by blueyed** [comment]
Oh, now I see that you are using version v3.4.13.

Sorry, but that is not supported - and takes us back to the initial issue: the README should state that version 3.5 is required.

**Comment by Spaghetti-Cat** [comment]
Yes it was in my initial post :P

OK, sorry to bother you. I'll take some time to migrate to v3.5. Thanks for writing this plugin anyway

**Comment by blueyed** [comment]
Yeah, it started with `gears` - which could be fixed, but `connect_signal` is the next one then etc..
I am planning to move to wiboxes etc, so...

..and you should move forward anyway.. ;D

**Comment by blueyed** [comment]
Should be fixed (as in documented) by now.
